{% set name = "parallelbar" %}
{% set version = "2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/parallelbar-{{ version }}.tar.gz
  sha256: 63453b7016515d2e26e1a532b484ba94c6208d147494eeb1e2a623b4b561c197

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - tqdm
    - colorama

test:
  imports:
    - parallelbar
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dubovikmaster/parallelbar
  summary: Parallel processing with progress bars
  description: |
     Parallelbar displays the progress of tasks in the process pool for Pool class methods such as map, 
     starmap (since 1.2 version), imap and imap_unordered. 
     Parallelbar is based on the tqdm module and the standard python multiprocessing library. 
     Also, it is possible to handle exceptions that occur within a separate process, 
     as well as set a timeout for the execution of a task by a process.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - eunos-1128
